Document: somecover
Title: Debian somecover Manual
Author: <insert document author here>
Abstract: This manual describes what somecover is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/somecover/somecover.sgml.gz

Format: postscript
Files: /usr/share/doc/somecover/somecover.ps.gz

Format: text
Files: /usr/share/doc/somecover/somecover.text.gz

Format: HTML
Index: /usr/share/doc/somecover/html/index.html
Files: /usr/share/doc/somecover/html/*.html

  
